[tool.poetry]
name = "stridesync-ui"
version = "0.1.0"
description = ""
authors = ["Patrick Walsh <pw4.2020@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.8.19"
flask = "^3.0.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
